namespace RouterTray.StoreScreenshotStudio;

internal sealed record StoreScreenshotLocalization(
    string CultureName,
    string StoreLocale,
    string PolicyHeadline,
    string PolicyDescription,
    string ProfilesHeadline,
    string ProfilesDescription,
    string ProfileSettingsCaption,
    string AccessTokenCaption,
    string ApplicationSettingsCaption,
    string HomeProfile,
    string OfficeProfile,
    string LabProfile,
    string DirectPolicy,
    string WorkVpnPolicy,
    string PrivacyVpnPolicy,
    string FamilyPolicy,
    string HomeNetwork,
    string OfficeNetwork,
    string LabNetwork)
{
    public static IReadOnlyList<StoreScreenshotLocalization> All { get; } =
    [
        new(
            "en-US",
            "en-US",
            "Your traffic.\nYour route.\nOne click.",
            "Switch Keenetic routing policies right from the Windows system tray instantly, without opening the router interface.",
            "Your network changes.\nYour profile follows.",
            "Bind a profile to each Windows network and RouterTray selects it automatically at home, at work, or in the lab.",
            "Configure router access, credentials, and Windows network bindings in one place.",
            "Sign in with an access token on supported Keenetic and Netcraze firmware.",
            "Choose automatic profile selection, Windows startup, and policy change notifications.",
            "Home", "Office", "Lab",
            "Direct", "Work VPN", "Privacy VPN", "Family",
            "Home Wi-Fi", "Office Ethernet", "Lab Wi-Fi"),
        new(
            "da-DK",
            "da-DK",
            "Din trafik.\nDin rute.\nÉt klik.",
            "Skift Keenetic-routingpolitikker direkte fra meddelelsesområdet i Windows – med det samme og uden at åbne routerens brugerflade.",
            "Dit netværk skifter.\nDin profil følger med.",
            "Knyt en profil til hvert Windows-netværk, så vælger RouterTray den automatisk derhjemme, på arbejdet eller i laboratoriet.",
            "Konfigurer routeradgang, legitimationsoplysninger og Windows-netværkstilknytninger samlet ét sted.",
            "Log på med et adgangstoken på understøttet Keenetic- og Netcraze-firmware.",
            "Vælg automatisk profilvalg, start med Windows og meddelelser ved skift af adgangspolitik.",
            "Hjem", "Kontor", "Lab",
            "Direkte", "Arbejds-VPN", "Privatlivs-VPN", "Familie",
            "Hjemme-Wi-Fi", "Kontor-Ethernet", "Lab-Wi-Fi"),
        new(
            "de-DE",
            "de-DE",
            "Ihr Datenverkehr.\nIhre Route.\nEin Klick.",
            "Wechseln Sie Keenetic-Routingrichtlinien sofort über den Windows-Infobereich, ohne die Routeroberfläche zu öffnen.",
            "Ihr Netzwerk\nändert sich.\nIhr Profil folgt.",
            "Verknüpfen Sie jedes Windows-Netzwerk mit einem Profil. RouterTray wählt es zu Hause, im Büro oder im Labor automatisch aus.",
            "Konfigurieren Sie Routerzugriff, Anmeldedaten und Windows-Netzwerkzuordnungen zentral an einem Ort.",
            "Melden Sie sich auf unterstützter Keenetic- und Netcraze-Firmware mit einem Zugriffstoken an.",
            "Wählen Sie automatische Profilauswahl, Start mit Windows und Benachrichtigungen bei Richtlinienwechseln.",
            "Zuhause", "Büro", "Labor",
            "Direkt", "Arbeits-VPN", "Datenschutz-VPN", "Familie",
            "Heim-WLAN", "Büro-Ethernet", "Labor-WLAN"),
        new(
            "es-ES",
            "es-ES",
            "Tu tráfico.\nTu ruta.\nUn clic.",
            "Cambia al instante las políticas de enrutamiento de Keenetic desde la bandeja del sistema de Windows, sin abrir la interfaz del router.",
            "Tu red cambia.\nTu perfil la sigue.",
            "Asocia un perfil a cada red de Windows y RouterTray lo seleccionará automáticamente en casa, en el trabajo o en el laboratorio.",
            "Configura el acceso al router, las credenciales y las asociaciones de red de Windows desde un solo lugar.",
            "Inicia sesión con un token de acceso en firmware compatible de Keenetic y Netcraze.",
            "Elige la selección automática de perfiles, el inicio con Windows y las notificaciones de cambio de política.",
            "Casa", "Oficina", "Laboratorio",
            "Directa", "VPN de trabajo", "VPN privada", "Familia",
            "Wi-Fi de casa", "Ethernet de oficina", "Wi-Fi del laboratorio"),
        new(
            "fi-FI",
            "fi-FI",
            "Liikenteesi.\nReittisi.\nYksi napsautus.",
            "Vaihda Keeneticin reitityskäytäntöjä heti Windowsin ilmaisinalueelta avaamatta reitittimen käyttöliittymää.",
            "Verkkosi vaihtuu.\nProfiilisi seuraa mukana.",
            "Liitä profiili kuhunkin Windows-verkkoon, niin RouterTray valitsee sen automaattisesti kotona, töissä tai laboratoriossa.",
            "Määritä reitittimen käyttöoikeudet, tunnistetiedot ja Windows-verkkojen sidonnat yhdessä paikassa.",
            "Kirjaudu käyttöoikeustunnuksella tuettuun Keenetic- tai Netcraze-laiteohjelmistoon.",
            "Valitse automaattinen profiilin valinta, käynnistys Windowsin mukana ja ilmoitukset käytäntöjen vaihdoista.",
            "Koti", "Toimisto", "Laboratorio",
            "Suora", "Työ-VPN", "Yksityisyys-VPN", "Perhe",
            "Kodin Wi-Fi", "Toimiston Ethernet", "Laboratorion Wi-Fi"),
        new(
            "fr-FR",
            "fr-FR",
            "Votre trafic.\nVotre route.\nUn clic.",
            "Changez instantanément de politique de routage Keenetic depuis la zone de notification Windows, sans ouvrir l’interface du routeur.",
            "Votre réseau change.\nVotre profil suit.",
            "Associez un profil à chaque réseau Windows : RouterTray le sélectionne automatiquement à la maison, au travail ou au laboratoire.",
            "Configurez l’accès au routeur, les identifiants et les associations aux réseaux Windows au même endroit.",
            "Connectez-vous avec un jeton d’accès sur les firmwares Keenetic et Netcraze compatibles.",
            "Choisissez la sélection automatique du profil, le démarrage avec Windows et les notifications de changement de politique.",
            "Domicile", "Bureau", "Labo",
            "Direct", "VPN professionnel", "VPN privé", "Famille",
            "Wi-Fi domicile", "Ethernet bureau", "Wi-Fi labo"),
        new(
            "it-IT",
            "it-IT",
            "Il tuo traffico.\nIl tuo percorso.\nUn clic.",
            "Cambia subito i criteri di routing Keenetic dall’area di notifica di Windows, senza aprire l’interfaccia del router.",
            "La rete cambia.\nIl profilo la segue.",
            "Associa un profilo a ogni rete Windows e RouterTray lo selezionerà automaticamente a casa, al lavoro o in laboratorio.",
            "Configura in un unico posto l’accesso al router, le credenziali e le associazioni alle reti Windows.",
            "Accedi con un token di accesso sui firmware Keenetic e Netcraze supportati.",
            "Scegli la selezione automatica del profilo, l’avvio con Windows e le notifiche al cambio di criterio.",
            "Casa", "Ufficio", "Laboratorio",
            "Diretto", "VPN lavoro", "VPN privacy", "Famiglia",
            "Wi-Fi di casa", "Ethernet ufficio", "Wi-Fi laboratorio"),
        new(
            "pl-PL",
            "pl-PL",
            "Twój ruch.\nTwoja trasa.\nJedno kliknięcie.",
            "Błyskawicznie przełączaj zasady routingu Keenetic z zasobnika systemowego Windows — bez otwierania interfejsu routera.",
            "Twoja sieć się zmienia.\nTwój profil podąża\nza nią.",
            "Przypisz profil do każdej sieci Windows, a RouterTray wybierze go automatycznie w domu, w pracy lub w laboratorium.",
            "Skonfiguruj w jednym miejscu dostęp do routera, dane logowania i powiązania z sieciami Windows.",
            "Loguj się tokenem dostępu w obsługiwanym oprogramowaniu Keenetic i Netcraze.",
            "Wybierz automatyczny wybór profilu, uruchamianie z systemem Windows i powiadomienia o zmianie zasad.",
            "Dom", "Biuro", "Laboratorium",
            "Bezpośrednio", "VPN służbowy", "VPN prywatności", "Rodzina",
            "Domowe Wi-Fi", "Biurowy Ethernet", "Wi-Fi laboratorium"),
        new(
            "pt-PT",
            "pt-PT",
            "O seu tráfego.\nA sua rota.\nUm clique.",
            "Altere instantaneamente as políticas de encaminhamento do Keenetic na área de notificação do Windows, sem abrir a interface do router.",
            "A sua rede muda.\nO seu perfil acompanha.",
            "Associe um perfil a cada rede Windows e o RouterTray seleciona-o automaticamente em casa, no trabalho ou no laboratório.",
            "Configure o acesso ao router, as credenciais e as associações de rede do Windows num único local.",
            "Inicie sessão com um token de acesso em firmware Keenetic e Netcraze compatível.",
            "Escolha a seleção automática de perfis, o arranque com o Windows e as notificações de mudança de política.",
            "Casa", "Escritório", "Laboratório",
            "Direta", "VPN de trabalho", "VPN de privacidade", "Família",
            "Wi-Fi de casa", "Ethernet do escritório", "Wi-Fi do laboratório"),
        new(
            "ru-RU",
            "ru-RU",
            "Ваш трафик.\nВаш маршрут.\nОдин клик.",
            "Мгновенно переключайте политики маршрутизации Keenetic из системного трея Windows, не открывая интерфейс роутера.",
            "Сеть меняется.\nПрофиль следует\nза ней.",
            "Привяжите профиль к каждой сети Windows — RouterTray автоматически выберет его дома, на работе или в лаборатории.",
            "Настраивайте доступ к роутеру, учётные данные и привязки к сетям Windows в одном месте.",
            "Входите с помощью токена доступа на поддерживаемых прошивках Keenetic и Netcraze.",
            "Настройте автоматический выбор профиля, запуск вместе с Windows и уведомления о смене политики.",
            "Дом", "Офис", "Лаборатория",
            "Напрямую", "Рабочий VPN", "Приватный VPN", "Семья",
            "Домашний Wi-Fi", "Офисный Ethernet", "Wi-Fi лаборатории"),
        new(
            "sv-SE",
            "sv-SE",
            "Din trafik.\nDin rutt.\nEtt klick.",
            "Växla Keenetic-routningsprinciper direkt från meddelandefältet i Windows utan att öppna routerns gränssnitt.",
            "Ditt nätverk ändras.\nDin profil följer med.",
            "Koppla en profil till varje Windows-nätverk så väljer RouterTray den automatiskt hemma, på jobbet eller i labbet.",
            "Konfigurera routeråtkomst, inloggningsuppgifter och Windows-nätverkskopplingar på ett och samma ställe.",
            "Logga in med en åtkomsttoken på fast programvara från Keenetic och Netcraze som stöds.",
            "Välj automatiskt profilval, start med Windows och aviseringar vid principbyte.",
            "Hemma", "Kontor", "Labb",
            "Direkt", "Jobb-VPN", "Sekretess-VPN", "Familj",
            "Hemma-Wi-Fi", "Kontors-Ethernet", "Labb-Wi-Fi"),
        new(
            "tr-TR",
            "tr-TR",
            "Trafiğiniz.\nRotanız.\nTek tık.",
            "Keenetic yönlendirme politikalarını yönlendirici arayüzünü açmadan doğrudan Windows sistem tepsisinden anında değiştirin.",
            "Ağınız değişir.\nProfiliniz onu izler.",
            "Her Windows ağına bir profil bağlayın; RouterTray evde, işte veya laboratuvarda doğru profili otomatik olarak seçsin.",
            "Yönlendirici erişimini, kimlik bilgilerini ve Windows ağ bağlantılarını tek bir yerden yapılandırın.",
            "Desteklenen Keenetic ve Netcraze ürün yazılımlarında erişim belirteciyle oturum açın.",
            "Otomatik profil seçimini, Windows ile başlangıcı ve politika değişikliği bildirimlerini ayarlayın.",
            "Ev", "Ofis", "Laboratuvar",
            "Doğrudan", "İş VPN'i", "Gizlilik VPN'i", "Aile",
            "Ev Wi-Fi", "Ofis Ethernet", "Laboratuvar Wi-Fi"),
        new(
            "uk-UA",
            "uk-UA",
            "Ваш трафік.\nВаш маршрут.\nОдин клік.",
            "Миттєво перемикайте політики маршрутизації Keenetic із системного трея Windows, не відкриваючи інтерфейс маршрутизатора.",
            "Мережа змінюється.\nПрофіль слідує\nза нею.",
            "Прив’яжіть профіль до кожної мережі Windows — RouterTray автоматично вибере його вдома, на роботі чи в лабораторії.",
            "Налаштовуйте доступ до маршрутизатора, облікові дані та прив’язки до мереж Windows в одному місці.",
            "Входьте за допомогою токена доступу на підтримуваних прошивках Keenetic і Netcraze.",
            "Налаштуйте автоматичний вибір профілю, запуск разом із Windows і сповіщення про зміну політики.",
            "Дім", "Офіс", "Лабораторія",
            "Напряму", "Робочий VPN", "Приватний VPN", "Родина",
            "Домашній Wi-Fi", "Офісний Ethernet", "Wi-Fi лабораторії")
    ];

    public string BuildCaptionsFile()
    {
        return string.Join(
            Environment.NewLine,
            "01-policy-switcher.png",
            PolicyDescription,
            string.Empty,
            "02-router-profiles.png",
            ProfilesDescription,
            string.Empty,
            "03-profile-settings.png",
            ProfileSettingsCaption,
            string.Empty,
            "04-access-token.png",
            AccessTokenCaption,
            string.Empty,
            "05-application-settings.png",
            ApplicationSettingsCaption,
            string.Empty);
    }
}
